version: '2'
services:
  yep_demo-app:
    image: yep_demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://yep_demo-postgresql:5432/yep_demo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  yep_demo-postgresql:
    extends:
      file: postgresql.yml
      service: yep_demo-postgresql
